language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '11'
  - '10'
  - '9'
  - '8'
script:
  - npm run build
  - npm test
after_success:
  - npm run semantic-release
branches:
  only:
    - master
